Controllers/AchievementController.cs
using System.Threading.Tasks;

using HackerRank.Responses;
using HackerRank.Services;
using HackerRank.ViewModels;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using HackerRank.Models.Users;
using Microsoft.AspNetCore.Identity;

namespace HackerRank.Controllers
{
    public class AchievementController : Controller
    {
        private readonly IAchievementService _achievementService;
        private readonly IUserService _userService;
        private readonly UserManager<User> _userManager;

        public AchievementController(IAchievementService achievementService, IUserService userService, UserManager<User> signInManager)
        {
            _achievementService = achievementService;
            _userService = userService;
            _userManager = signInManager;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(await _achievementService.ListAllAchievements(user.NormalizedUserName));
        }

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AchievementViewModel achievement = await _achievementService.Details((int)id);

            return View(achievement);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SetShowcase()
        {
            var achievementIds = Request.Form["IsChecked"].ToList();
            var user = await _userManager.GetUserAsync(User);
            await _achievementService.SetShowCase(achievementIds, user.NormalizedUserName);

            return RedirectToAction("profile", "user", new { id = user.UserName });
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("AchievementId,AchievementName,Description,NumberOfActions,TypeOfAction")] AchievementResponse achievementModel, [FromForm(Name = "file")] IFormFile file)
        {
            if (ModelState.IsValid)
            {
                await _achievementService.Create(achievementModel, file);
                return RedirectToAction(nameof(Index));
            }
            return View(achievementModel);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var achievement = await _achievementService.FindAchievementModelById((int)id);

            if (achievement == null)
            {
                return NotFound();
            }
            return View(achievement);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("AchievementId,AchievementName,Description,NumberOfActions,TypeOfAction")] AchievementResponse achievementModel, [FromForm(Name = "editFile")] IFormFile file)
        {
            if (id != achievementModel.AchievementId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _achievementService.Edit(achievementModel, file);
                return RedirectToAction(nameof(Index));
            }

            return View(achievementModel);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var achievement = await _achievementService.FindAchievementById((int)id);
            if (achievement == null)
            {
                return NotFound();
            }

            return View(achievement);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _achievementService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HackerRank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/newIndex.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="max-width: 200px" alt="Logo" src="~/img/logo.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Achievement" asp-action="Index">Achievements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Data">Get data</a>
                        </li>
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/Hangfire" add target="_blank">Hangfire</a>
                            </li>
                        }
                        <li class="dropdown nav-item">
                            <input class="dropdown-toggle form-control" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" type="text" placeholder="Search for users" />
                            <div id="dropdownMenu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            </div>
                        </li>                   
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    
        
            @RenderBody()
        
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HackerRank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>